"use strict";
const fs                  = require('fs');
const RedeemCodeGenerator = require('./RedeemCodeGenerator');
const encryptDirectionMap = JSON.parse(fs.readFileSync('./cryptMap/EncryptDirectionMap.json'));
const encryptNumberMap    = JSON.parse(fs.readFileSync('./cryptMap/EncryptNumberMap.json'));
const decryptDirectionMap = JSON.parse(fs.readFileSync('./cryptMap/DecryptDirectionMap.json'));
const decryptNumberMap    = JSON.parse(fs.readFileSync('./cryptMap/DecryptNumberMap.json'));

const redeemCode = new RedeemCodeGenerator('sagwangho.com', encryptDirectionMap, encryptNumberMap, decryptDirectionMap, decryptNumberMap);

console.log(redeemCode.generate(1, 1, 1));
console.log(redeemCode.generate(2, 1, 1));
console.log(redeemCode.generate(3, 1, 1));
console.log(redeemCode.generate(4, 1, 1));
console.log(redeemCode.generate(5, 1, 1));
console.log(redeemCode.generate(6, 1, 1));
console.log(redeemCode.generate(100, 30000000, 30000000));
console.log(redeemCode.validate('64U5855NFD5H'));
console.log(redeemCode.validate('QLI6N9VY7BI5'));
console.log(redeemCode.validate('07KXMZ1N790T'));
console.log(redeemCode.validate('1M8ZM8R3MMOH'));
console.log(redeemCode.validate('2BXZ3D2I2OW2'));
console.log(redeemCode.validate('34740XJ4X947'));
console.log(redeemCode.validate('4DIFD4WN3DEF'));
console.log(redeemCode.validate('555Q865456B0'));
console.log(redeemCode.validate('6495V55NFVCK'));
console.log(redeemCode.validate('7MANSGSQXXMX'));
console.log(redeemCode.validate('88PTJ0218JJ6'));
console.log(redeemCode.validate('9PF6RF766X6O'));
console.log(redeemCode.validate('AWWRDIR1WMGK'));
console.log(redeemCode.validate('BAUA4FOQAA34'));
console.log(redeemCode.validate('CFI4MFUSM7CX'));
console.log(redeemCode.validate('D766ZZ6C7QU6'));
console.log(redeemCode.validate('EMORPBBQFT72'));
console.log(redeemCode.validate('F46CRCX33CXS'));
console.log(redeemCode.validate('GGUGL8MRX1G0'));
console.log(redeemCode.validate('HX245G5M2M22'));
console.log(redeemCode.validate('IV9934A0554H'));
console.log(redeemCode.validate('JZZZWWZCDX6A'));
console.log(redeemCode.validate('K9URTLX8YCCC'));
console.log(redeemCode.validate('L97770M7OAIO'));
console.log(redeemCode.validate('MRRLSQORPLVT'));
console.log(redeemCode.validate('NL66L6L7Q6PL'));
console.log(redeemCode.validate('O721Q775GIV5'));
console.log(redeemCode.validate('PYRXGV1X3YXX'));
console.log(redeemCode.validate('QLV05KVYQ0G0'));
console.log(redeemCode.validate('R93RWW13WH9W'));
console.log(redeemCode.validate('SVI4IIQ80AKH'));
console.log(redeemCode.validate('TK7ZZZSZVO97'));
console.log(redeemCode.validate('UT9TI3EKLTTW'));
console.log(redeemCode.validate('VBBEUUZSJ7UZ'));
console.log(redeemCode.validate('WJ9DYDNT9DOA'));
console.log(redeemCode.validate('XJ3JYJ3JBQMQ'));
console.log(redeemCode.validate('YAG05GZGEQ8I'));
console.log(redeemCode.validate('ZTTXXHTN38TY'));